### ISSUE TITLE
楼主，我有分析你的代码，但是找不到数据接口，不知道你的代码的数据从哪里请求的哇

### ISSUE THREAD

**Issue by JserJser** [zhen-ke/react-cnode#1]
楼主你的项目写的非常有意思~
我仔细分析代码之后，发现连数据接口都没有找到，还有登陆那个accessToken，我没有找到登陆进去的方法~对了http.js之中的这个https://cnodejs.org/api/v1是数据接口吗？我打开是not get~~~

**Comment by zhen-ke** [comment]
在actionCreators.js里，每个组件有都自己的actionCreators.js

> 楼主你的项目写的非常有意思~
> 我仔细分析代码之后，发现连数据接口都没有找到，还有登陆那个accessToken，我没有找到登陆进去的方法~对了http.js之中的这个[https://cnodejs.org/api/v1是数据接口吗？我打开是not](https://cnodejs.org/api/v1%E6%98%AF%E6%95%B0%E6%8D%AE%E6%8E%A5%E5%8F%A3%E5%90%97%EF%BC%9F%E6%88%91%E6%89%93%E5%BC%80%E6%98%AFnot) get~~~
